/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.web;

import org.xtext.example.mydsl2.web.AbstractMyDslWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class MyDslWebModule extends AbstractMyDslWebModule {
}
