/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.web;

import java.util.concurrent.ExecutorService;

/**
 * Initialization support for running Xtext languages in web applications.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class MyDslWebSetup /* implements MyDslStandaloneSetup  */{
  private final /* Provider<ExecutorService> */Object executorServiceProvider;
  
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nMyDslRuntimeModule cannot be resolved."
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules is undefined"
      + "\nInvalid number of arguments. The constructor MyDslWebModule() is not applicable for the arguments (Provider)"
      + "\ncreateInjector cannot be resolved"
      + "\noverride cannot be resolved"
      + "\nwith cannot be resolved");
  }
}
